#cloud-config
package_upgrade: true
packages:
  - apache2
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker.io
runcmd:
  - git clone https://github.com/sjohner/jhnr.ch.git src
  - git clone https://github.com/sjohner/hyde.git src/themes/hyde
  - docker run --rm --name "hugo" -v $(pwd)/src:/src -v $(pwd)/output:/output -e HUGO_THEME="hyde" jojomi/hugo
  - mv $(pwd)/output/* /var/www/html/
  - service apache2 reload
